# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jonashaffky/Dokumente/Studium/Computergrafik/CGLab_-Haffky117185_Tobollik118988

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jonashaffky/Dokumente/Studium/Computergrafik/CGLab_-Haffky117185_Tobollik118988

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"dev\" \"runtime\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jonashaffky/Dokumente/Studium/Computergrafik/CGLab_-Haffky117185_Tobollik118988/CMakeFiles /home/jonashaffky/Dokumente/Studium/Computergrafik/CGLab_-Haffky117185_Tobollik118988/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jonashaffky/Dokumente/Studium/Computergrafik/CGLab_-Haffky117185_Tobollik118988/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named framework

# Build rule for target.
framework: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 framework
.PHONY : framework

# fast build rule for target.
framework/fast:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/build
.PHONY : framework/fast

#=============================================================================
# Target rules for targets named solar_system

# Build rule for target.
solar_system: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 solar_system
.PHONY : solar_system

# fast build rule for target.
solar_system/fast:
	$(MAKE) -f CMakeFiles/solar_system.dir/build.make CMakeFiles/solar_system.dir/build
.PHONY : solar_system/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f external/glfw-3.1.1/src/CMakeFiles/glfw.dir/build.make external/glfw-3.1.1/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named glbinding

# Build rule for target.
glbinding: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glbinding
.PHONY : glbinding

# fast build rule for target.
glbinding/fast:
	$(MAKE) -f external/glbinding-2.1.1/source/glbinding/CMakeFiles/glbinding.dir/build.make external/glbinding-2.1.1/source/glbinding/CMakeFiles/glbinding.dir/build
.PHONY : glbinding/fast

application/source/application_solar.o: application/source/application_solar.cpp.o

.PHONY : application/source/application_solar.o

# target to build an object file
application/source/application_solar.cpp.o:
	$(MAKE) -f CMakeFiles/solar_system.dir/build.make CMakeFiles/solar_system.dir/application/source/application_solar.cpp.o
.PHONY : application/source/application_solar.cpp.o

application/source/application_solar.i: application/source/application_solar.cpp.i

.PHONY : application/source/application_solar.i

# target to preprocess a source file
application/source/application_solar.cpp.i:
	$(MAKE) -f CMakeFiles/solar_system.dir/build.make CMakeFiles/solar_system.dir/application/source/application_solar.cpp.i
.PHONY : application/source/application_solar.cpp.i

application/source/application_solar.s: application/source/application_solar.cpp.s

.PHONY : application/source/application_solar.s

# target to generate assembly for a file
application/source/application_solar.cpp.s:
	$(MAKE) -f CMakeFiles/solar_system.dir/build.make CMakeFiles/solar_system.dir/application/source/application_solar.cpp.s
.PHONY : application/source/application_solar.cpp.s

external/tinyobjloader-aa07206/tiny_obj_loader.o: external/tinyobjloader-aa07206/tiny_obj_loader.cc.o

.PHONY : external/tinyobjloader-aa07206/tiny_obj_loader.o

# target to build an object file
external/tinyobjloader-aa07206/tiny_obj_loader.cc.o:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/external/tinyobjloader-aa07206/tiny_obj_loader.cc.o
.PHONY : external/tinyobjloader-aa07206/tiny_obj_loader.cc.o

external/tinyobjloader-aa07206/tiny_obj_loader.i: external/tinyobjloader-aa07206/tiny_obj_loader.cc.i

.PHONY : external/tinyobjloader-aa07206/tiny_obj_loader.i

# target to preprocess a source file
external/tinyobjloader-aa07206/tiny_obj_loader.cc.i:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/external/tinyobjloader-aa07206/tiny_obj_loader.cc.i
.PHONY : external/tinyobjloader-aa07206/tiny_obj_loader.cc.i

external/tinyobjloader-aa07206/tiny_obj_loader.s: external/tinyobjloader-aa07206/tiny_obj_loader.cc.s

.PHONY : external/tinyobjloader-aa07206/tiny_obj_loader.s

# target to generate assembly for a file
external/tinyobjloader-aa07206/tiny_obj_loader.cc.s:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/external/tinyobjloader-aa07206/tiny_obj_loader.cc.s
.PHONY : external/tinyobjloader-aa07206/tiny_obj_loader.cc.s

framework/source/PointLightNode.o: framework/source/PointLightNode.cpp.o

.PHONY : framework/source/PointLightNode.o

# target to build an object file
framework/source/PointLightNode.cpp.o:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/framework/source/PointLightNode.cpp.o
.PHONY : framework/source/PointLightNode.cpp.o

framework/source/PointLightNode.i: framework/source/PointLightNode.cpp.i

.PHONY : framework/source/PointLightNode.i

# target to preprocess a source file
framework/source/PointLightNode.cpp.i:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/framework/source/PointLightNode.cpp.i
.PHONY : framework/source/PointLightNode.cpp.i

framework/source/PointLightNode.s: framework/source/PointLightNode.cpp.s

.PHONY : framework/source/PointLightNode.s

# target to generate assembly for a file
framework/source/PointLightNode.cpp.s:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/framework/source/PointLightNode.cpp.s
.PHONY : framework/source/PointLightNode.cpp.s

framework/source/application.o: framework/source/application.cpp.o

.PHONY : framework/source/application.o

# target to build an object file
framework/source/application.cpp.o:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/framework/source/application.cpp.o
.PHONY : framework/source/application.cpp.o

framework/source/application.i: framework/source/application.cpp.i

.PHONY : framework/source/application.i

# target to preprocess a source file
framework/source/application.cpp.i:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/framework/source/application.cpp.i
.PHONY : framework/source/application.cpp.i

framework/source/application.s: framework/source/application.cpp.s

.PHONY : framework/source/application.s

# target to generate assembly for a file
framework/source/application.cpp.s:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/framework/source/application.cpp.s
.PHONY : framework/source/application.cpp.s

framework/source/camera_node.o: framework/source/camera_node.cpp.o

.PHONY : framework/source/camera_node.o

# target to build an object file
framework/source/camera_node.cpp.o:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/framework/source/camera_node.cpp.o
.PHONY : framework/source/camera_node.cpp.o

framework/source/camera_node.i: framework/source/camera_node.cpp.i

.PHONY : framework/source/camera_node.i

# target to preprocess a source file
framework/source/camera_node.cpp.i:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/framework/source/camera_node.cpp.i
.PHONY : framework/source/camera_node.cpp.i

framework/source/camera_node.s: framework/source/camera_node.cpp.s

.PHONY : framework/source/camera_node.s

# target to generate assembly for a file
framework/source/camera_node.cpp.s:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/framework/source/camera_node.cpp.s
.PHONY : framework/source/camera_node.cpp.s

framework/source/geometry_node.o: framework/source/geometry_node.cpp.o

.PHONY : framework/source/geometry_node.o

# target to build an object file
framework/source/geometry_node.cpp.o:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/framework/source/geometry_node.cpp.o
.PHONY : framework/source/geometry_node.cpp.o

framework/source/geometry_node.i: framework/source/geometry_node.cpp.i

.PHONY : framework/source/geometry_node.i

# target to preprocess a source file
framework/source/geometry_node.cpp.i:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/framework/source/geometry_node.cpp.i
.PHONY : framework/source/geometry_node.cpp.i

framework/source/geometry_node.s: framework/source/geometry_node.cpp.s

.PHONY : framework/source/geometry_node.s

# target to generate assembly for a file
framework/source/geometry_node.cpp.s:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/framework/source/geometry_node.cpp.s
.PHONY : framework/source/geometry_node.cpp.s

framework/source/model.o: framework/source/model.cpp.o

.PHONY : framework/source/model.o

# target to build an object file
framework/source/model.cpp.o:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/framework/source/model.cpp.o
.PHONY : framework/source/model.cpp.o

framework/source/model.i: framework/source/model.cpp.i

.PHONY : framework/source/model.i

# target to preprocess a source file
framework/source/model.cpp.i:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/framework/source/model.cpp.i
.PHONY : framework/source/model.cpp.i

framework/source/model.s: framework/source/model.cpp.s

.PHONY : framework/source/model.s

# target to generate assembly for a file
framework/source/model.cpp.s:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/framework/source/model.cpp.s
.PHONY : framework/source/model.cpp.s

framework/source/model_loader.o: framework/source/model_loader.cpp.o

.PHONY : framework/source/model_loader.o

# target to build an object file
framework/source/model_loader.cpp.o:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/framework/source/model_loader.cpp.o
.PHONY : framework/source/model_loader.cpp.o

framework/source/model_loader.i: framework/source/model_loader.cpp.i

.PHONY : framework/source/model_loader.i

# target to preprocess a source file
framework/source/model_loader.cpp.i:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/framework/source/model_loader.cpp.i
.PHONY : framework/source/model_loader.cpp.i

framework/source/model_loader.s: framework/source/model_loader.cpp.s

.PHONY : framework/source/model_loader.s

# target to generate assembly for a file
framework/source/model_loader.cpp.s:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/framework/source/model_loader.cpp.s
.PHONY : framework/source/model_loader.cpp.s

framework/source/node.o: framework/source/node.cpp.o

.PHONY : framework/source/node.o

# target to build an object file
framework/source/node.cpp.o:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/framework/source/node.cpp.o
.PHONY : framework/source/node.cpp.o

framework/source/node.i: framework/source/node.cpp.i

.PHONY : framework/source/node.i

# target to preprocess a source file
framework/source/node.cpp.i:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/framework/source/node.cpp.i
.PHONY : framework/source/node.cpp.i

framework/source/node.s: framework/source/node.cpp.s

.PHONY : framework/source/node.s

# target to generate assembly for a file
framework/source/node.cpp.s:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/framework/source/node.cpp.s
.PHONY : framework/source/node.cpp.s

framework/source/scene_graph.o: framework/source/scene_graph.cpp.o

.PHONY : framework/source/scene_graph.o

# target to build an object file
framework/source/scene_graph.cpp.o:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/framework/source/scene_graph.cpp.o
.PHONY : framework/source/scene_graph.cpp.o

framework/source/scene_graph.i: framework/source/scene_graph.cpp.i

.PHONY : framework/source/scene_graph.i

# target to preprocess a source file
framework/source/scene_graph.cpp.i:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/framework/source/scene_graph.cpp.i
.PHONY : framework/source/scene_graph.cpp.i

framework/source/scene_graph.s: framework/source/scene_graph.cpp.s

.PHONY : framework/source/scene_graph.s

# target to generate assembly for a file
framework/source/scene_graph.cpp.s:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/framework/source/scene_graph.cpp.s
.PHONY : framework/source/scene_graph.cpp.s

framework/source/shader_loader.o: framework/source/shader_loader.cpp.o

.PHONY : framework/source/shader_loader.o

# target to build an object file
framework/source/shader_loader.cpp.o:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/framework/source/shader_loader.cpp.o
.PHONY : framework/source/shader_loader.cpp.o

framework/source/shader_loader.i: framework/source/shader_loader.cpp.i

.PHONY : framework/source/shader_loader.i

# target to preprocess a source file
framework/source/shader_loader.cpp.i:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/framework/source/shader_loader.cpp.i
.PHONY : framework/source/shader_loader.cpp.i

framework/source/shader_loader.s: framework/source/shader_loader.cpp.s

.PHONY : framework/source/shader_loader.s

# target to generate assembly for a file
framework/source/shader_loader.cpp.s:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/framework/source/shader_loader.cpp.s
.PHONY : framework/source/shader_loader.cpp.s

framework/source/texture_loader.o: framework/source/texture_loader.cpp.o

.PHONY : framework/source/texture_loader.o

# target to build an object file
framework/source/texture_loader.cpp.o:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/framework/source/texture_loader.cpp.o
.PHONY : framework/source/texture_loader.cpp.o

framework/source/texture_loader.i: framework/source/texture_loader.cpp.i

.PHONY : framework/source/texture_loader.i

# target to preprocess a source file
framework/source/texture_loader.cpp.i:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/framework/source/texture_loader.cpp.i
.PHONY : framework/source/texture_loader.cpp.i

framework/source/texture_loader.s: framework/source/texture_loader.cpp.s

.PHONY : framework/source/texture_loader.s

# target to generate assembly for a file
framework/source/texture_loader.cpp.s:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/framework/source/texture_loader.cpp.s
.PHONY : framework/source/texture_loader.cpp.s

framework/source/utils.o: framework/source/utils.cpp.o

.PHONY : framework/source/utils.o

# target to build an object file
framework/source/utils.cpp.o:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/framework/source/utils.cpp.o
.PHONY : framework/source/utils.cpp.o

framework/source/utils.i: framework/source/utils.cpp.i

.PHONY : framework/source/utils.i

# target to preprocess a source file
framework/source/utils.cpp.i:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/framework/source/utils.cpp.i
.PHONY : framework/source/utils.cpp.i

framework/source/utils.s: framework/source/utils.cpp.s

.PHONY : framework/source/utils.s

# target to generate assembly for a file
framework/source/utils.cpp.s:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/framework/source/utils.cpp.s
.PHONY : framework/source/utils.cpp.s

framework/source/window_handler.o: framework/source/window_handler.cpp.o

.PHONY : framework/source/window_handler.o

# target to build an object file
framework/source/window_handler.cpp.o:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/framework/source/window_handler.cpp.o
.PHONY : framework/source/window_handler.cpp.o

framework/source/window_handler.i: framework/source/window_handler.cpp.i

.PHONY : framework/source/window_handler.i

# target to preprocess a source file
framework/source/window_handler.cpp.i:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/framework/source/window_handler.cpp.i
.PHONY : framework/source/window_handler.cpp.i

framework/source/window_handler.s: framework/source/window_handler.cpp.s

.PHONY : framework/source/window_handler.s

# target to generate assembly for a file
framework/source/window_handler.cpp.s:
	$(MAKE) -f CMakeFiles/framework.dir/build.make CMakeFiles/framework.dir/framework/source/window_handler.cpp.s
.PHONY : framework/source/window_handler.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... framework"
	@echo "... solar_system"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... glfw"
	@echo "... glbinding"
	@echo "... application/source/application_solar.o"
	@echo "... application/source/application_solar.i"
	@echo "... application/source/application_solar.s"
	@echo "... external/tinyobjloader-aa07206/tiny_obj_loader.o"
	@echo "... external/tinyobjloader-aa07206/tiny_obj_loader.i"
	@echo "... external/tinyobjloader-aa07206/tiny_obj_loader.s"
	@echo "... framework/source/PointLightNode.o"
	@echo "... framework/source/PointLightNode.i"
	@echo "... framework/source/PointLightNode.s"
	@echo "... framework/source/application.o"
	@echo "... framework/source/application.i"
	@echo "... framework/source/application.s"
	@echo "... framework/source/camera_node.o"
	@echo "... framework/source/camera_node.i"
	@echo "... framework/source/camera_node.s"
	@echo "... framework/source/geometry_node.o"
	@echo "... framework/source/geometry_node.i"
	@echo "... framework/source/geometry_node.s"
	@echo "... framework/source/model.o"
	@echo "... framework/source/model.i"
	@echo "... framework/source/model.s"
	@echo "... framework/source/model_loader.o"
	@echo "... framework/source/model_loader.i"
	@echo "... framework/source/model_loader.s"
	@echo "... framework/source/node.o"
	@echo "... framework/source/node.i"
	@echo "... framework/source/node.s"
	@echo "... framework/source/scene_graph.o"
	@echo "... framework/source/scene_graph.i"
	@echo "... framework/source/scene_graph.s"
	@echo "... framework/source/shader_loader.o"
	@echo "... framework/source/shader_loader.i"
	@echo "... framework/source/shader_loader.s"
	@echo "... framework/source/texture_loader.o"
	@echo "... framework/source/texture_loader.i"
	@echo "... framework/source/texture_loader.s"
	@echo "... framework/source/utils.o"
	@echo "... framework/source/utils.i"
	@echo "... framework/source/utils.s"
	@echo "... framework/source/window_handler.o"
	@echo "... framework/source/window_handler.i"
	@echo "... framework/source/window_handler.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

